version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: WebApp.Web/Dockerfile
    image: webapp-web-image:latest
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - api  # Make sure the API is available first
    networks:
      - webapp-network

  api:
    build:
      context: .
      dockerfile: WebApp.Api/Dockerfile
    image: webapp-api-image:latest
    ports:
      - "7145:7145"
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge

# networks:
#   default:
#     driver: bridge

#   mysql:
#     image: mysql:8.0
#     volumes:
#       - web-mysql-data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: webapp

# volumes:
#   web-mysql-data: